
// This file was auto-generated by ML.NET Model Builder. 

using Income_Console;

// Create single instance of sample data from first line of dataset for model input
Income.ModelInput sampleData = new Income.ModelInput()
{
    Age = 38F,
    Educational_num = 9F,
    Race = @"White",
    Gender = @"Male",
    Hours_per_week = 50F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Income with predicted Income from sample data...\n\n");


Console.WriteLine($"Age: {38F}");
Console.WriteLine($"Educational_num: {9F}");
Console.WriteLine($"Race: {@"White"}");
Console.WriteLine($"Gender: {@"Male"}");
Console.WriteLine($"Hours_per_week: {50F}");
Console.WriteLine($"Income: {@"<=50K"}");


var sortedScoresWithLabel = Income.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

